### ISSUE TITLE
Optimal "minimum time between entity updates"

### ISSUE THREAD

**Issue by ianfretwell** [robbinjanssen/home-assistant-omnik-inverter#100]
Hi  -  not an issue as such, more a request for assistance.

Is there an optimal setting for the "minimum time between entity updates" in the Configure settings ?

I have tried 4  and  5 minutes and on either I see the following type of results - notice the frequent inability to get any results. The wifi doesn't seem to be dropping to the inverter so I just thought there might be a 'better' value to be using for more consistent results.

![image](https://user-images.githubusercontent.com/52041704/154254600-51d38018-1886-4f78-af46-0089eedf1ebb.png)

Thanks.

**Comment by robbinjanssen** [comment]
Hi @ianfretwell,

Can you tell us a bit more about your setup? Like what inverter do you use?

Although you don't say that the wifi drops, it seems like a connection issue. Maybe add a binary_sensor and ping your inverter for a while? See if the connection drops?

Add this to your configuration.yaml

```
binary_sensor:
  - platform: ping
    host: x.x.x.x
    name: "My Inverter"
    count: 2
    scan_interval: 60
```
