### ISSUE TITLE
Home assistant's Energy Dashboard

### ISSUE THREAD

**Issue by mobiledude** [robbinjanssen/home-assistant-omnik-inverter#40]
Latest Beta of HA contains an energy Dashboard. Would love to be able to use this integration to get the Energy out of the omnik invertor. However the entities must have specific characteristics to support this. Can you please have a look if this is something that can be supported? Would be great.  https://rc.home-assistant.io/blog/2021/07/28/release-20218/

**Comment by freddieleeman** [comment]
For now, if you want to add `sensor.solar_power_total` to the Home Assistant Energy dashboard, just add this to your configuration.yaml:

```
homeassistant:
  customize_glob:
    sensor.solar_power_total:
      device_class: energy
      state_class: measurement
      last_reset: "1970-01-01T00:00:00+00:00"
```

**Comment by wes1993** [comment]
Hello,
This should be wonderful but can we also add the power_current and power_today?
I'm have this in my HA config but can't see the sensor some suggestion?:

```
homeassistant:
  customize_glob:
    sensor.solar_power_total:
      device_class: energy
      state_class: measurement
      last_reset: "1970-01-01T00:00:00+00:00"
```

I can see the last reset value in my developer tools page

Best Regards
Stefano
